### ISSUE TITLE
NPE on startup: AEAspectRegister.registerTEItems

### ISSUE THREAD

**Issue by Kaedenn** [Nividica/ThaumicEnergistics#153]
http://codepad.org/X0q4o0Ij

java.lang.NullPointerException
	at thaumicenergistics.registries.AEAspectRegister.registerTEItems(AEAspectRegister.java:1001) ~[AEAspectRegister.class:?]
	at thaumicenergistics.registries.AEAspectRegister.registerAEAspects(AEAspectRegister.java:1119) ~[AEAspectRegister.class:?]

Basically, it's in this line:
	AspectList cellAspects = ThaumcraftApiHelper.getObjectAspects( AEApi.instance().items().itemCell1k.stack( 1 ) ).copy();

All loaded mods are included in the paste above.

**Comment by Nividica** [comment]
See #147 for details.

**Comment by katur239** [comment]
Update Ae to Rv2 Beta 18.

**Comment by Kaedenn** [comment]
Thank you.
