### ISSUE TITLE
Java 1.7 "HashMap.getOrDefault" crash.

### ISSUE THREAD

**Issue by TATDK** [Nividica/ThaumicEnergistics#270]
```
java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at thaumicenergistics.common.integration.tc.GolemHooks.hook_SetupGolem(GolemHooks.java:621)
	at thaumcraft.common.entities.golems.EntityGolemBase.setupGolem(EntityGolemBase.java:288)
	at thaumcraft.common.entities.golems.EntityGolemBase.setup(EntityGolemBase.java:323)
	at thaumcraft.common.entities.golems.ItemGolemPlacer.spawnCreature(ItemGolemPlacer.java:233)
	at thaumcraft.common.entities.golems.ItemGolemPlacer.onItemUseFirst(ItemGolemPlacer.java:167)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:360)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Full crash log : https://ss.chikachi.net/crash-2016-01-29_17.10.04-server.txt

**Comment by Nividica** [comment]
Looks like "java.util.HashMap.getOrDefault" is a Java 1.8 function, which I did not realize. Unfortunately I use that call all over the place. Updating Java will fix the issue, but I will update the calls at some point in the future to make it Java 1.7 compatible.

**Comment by JennyLeeP** [comment]
Is there going to be a build for 1.7.10 that includes this fix ?

**Comment by ExDomino** [comment]
On 1.7.10 version of Minecraft, what exactly I have to update to prevent this crash again? What of your mod are causing the bug and what version should I use?

**Comment by Nividica** [comment]
java.util.HashMap.getOrDefault is a method added in java 8 that was not present in java 7. Attempting to use the mod with java 7 will result in this crash.

**Comment by ExDomino** [comment]
Updated to Java 8, no more crashing. Solved.
