### ISSUE TITLE
Client crash when getting view cells

### ISSUE THREAD

**Issue by ArcasCZ** [Nividica/ThaumicEnergistics#274]
http://pastebin.com/b7CQP3D0

Sorry for long paste, it's automatically generated by our client.

**Comment by Nividica** [comment]
Leaving this here for my reference
==========================
java.lang.NullPointerException
    at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.getViewCells(ContainerPartArcaneCraftingTerminal.java:614) ~[ContainerPartArcaneCraftingTerminal.class:?]
    at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.updateGUIViewCells(ContainerPartArcaneCraftingTerminal.java:748) ~[ContainerPartArcaneCraftingTerminal.class:?]

**Comment by KindarConrath** [comment]
Just bumped into the same issue when I tried to swap my armor in the terminal.

**Comment by Deregorn** [comment]
I'm having the same issue. Here's my crash log, maybe it is helpful:
[http://pastebin.com/jcq4hmfX](http://pastebin.com/jcq4hmfX)

**Comment by tollus** [comment]
Hey @Nividica , could it be this line returning null?

https://github.com/Nividica/ThaumicEnergistics/blob/master/src/main/java/thaumicenergistics/common/container/ContainerPartArcaneCraftingTerminal.java#L611
