### ISSUE TITLE
Crash when crafting essentia storage cells in terminal

### ISSUE THREAD

**Issue by TATDK** [Nividica/ThaumicEnergistics#275]
Version 1.0.0.1

```
java.lang.NullPointerException: Unexpected error
    at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.getViewCells(ContainerPartArcaneCraftingTerminal.java:608)
    at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.updateGUIViewCells(ContainerPartArcaneCraftingTerminal.java:742)
    at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.onViewCellChange(ContainerPartArcaneCraftingTerminal.java:1493)
    at thaumicenergistics.common.parts.PartArcaneCraftingTerminal.notifyListeners(PartArcaneCraftingTerminal.java:195)
    at thaumicenergistics.common.parts.PartArcaneCraftingTerminal.func_70299_a(PartArcaneCraftingTerminal.java:818)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
    at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1062)
    at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
    at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full crash log : https://pastebin.com/QX4mnJxV

**Comment by Nividica** [comment]
Hmm, seems like the same issue as #274. I will go ahead and close this one and post updates on #274.
