### ISSUE TITLE
Client crash when accessing Arcane Crafting Terminal

### ISSUE THREAD

**Issue by baddogg1231** [Nividica/ThaumicEnergistics#277]
I'm getting a client crash to desktop when trying to use the Arcane Crafting terminal. I've tried many different versions of AE2 and of ThaumicEnergistics, but nothing seems to fix the crash. Anyone on the server also gets a crash but not to desktop. 

 [21:40:01] [Netty Client IO #1/DEBUG] [OpenMods/]: openmods.network.IdSyncManager.onDisconnect(IdSyncManager.java:124): Disconnected, restoring local data
[21:40:02] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2/13/16 9:40 PM
Description: Unexpected error

java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at thaumicenergistics.common.container.TheContainerBase.getSlotOrNull(TheContainerBase.java:85)
	at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.getViewCells(ContainerPartArcaneCraftingTerminal.java:605)
	at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.updateGUIViewCells(ContainerPartArcaneCraftingTerminal.java:742)
	at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.onViewCellChange(ContainerPartArcaneCraftingTerminal.java:1493)
	at thaumicenergistics.common.parts.PartArcaneCraftingTerminal.notifyListeners(PartArcaneCraftingTerminal.java:195)
	at thaumicenergistics.common.parts.PartArcaneCraftingTerminal.func_70299_a(PartArcaneCraftingTerminal.java:818)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1062)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thaumicenergistics.common.container.TheContainerBase.getSlotOrNull(TheContainerBase.java:85)
	at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.getViewCells(ContainerPartArcaneCraftingTerminal.java:605)
	at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.updateGUIViewCells(ContainerPartArcaneCraftingTerminal.java:742)
	at thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.onViewCellChange(ContainerPartArcaneCraftingTerminal.java:1493)
	at thaumicenergistics.common.parts.PartArcaneCraftingTerminal.notifyListeners(PartArcaneCraftingTerminal.java:195)
	at thaumicenergistics.common.parts.PartArcaneCraftingTerminal.func_70299_a(PartArcaneCraftingTerminal.java:818)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1062)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['baddogg1231'/15437, l='MpServer', x=-346.16, y=56.62, z=-333.69]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-155,64,-145), Chunk: (at 5,4,15 in -10,-10; contains blocks -160,0,-160 to -145,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 8836112 game time, 2829279 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 93 total; [EntityMobEnderman['Enderman'/17058, l='MpServer', x=-337.50, y=7.00, z=-261.50], EntitySkeleton['Skeleton'/18986, l='MpServer', x=-292.50, y=21.00, z=-331.50], EntityHuman['Bopogamel'/15802, l='MpServer', x=-329.44, y=36.00, z=-248.44], EntityHuman['Imalune'/18484, l='MpServer', x=-328.50, y=16.00, z=-226.50], EntityHuman['KakerMix'/17299, l='MpServer', x=-326.50, y=32.00, z=-277.50], EntityGiantBrainyZombie['Furious Zombie'/16809, l='MpServer', x=-363.00, y=63.00, z=-353.56], EntityItem['item.item.dyePowder.black'/19553, l='MpServer', x=-391.56, y=60.13, z=-288.56], EntityItem['item.item.ganyssurface.poop'/12184, l='MpServer', x=-331.72, y=31.13, z=-289.19], EntityGiantBrainyZombie['Furious Zombie'/17663, l='MpServer', x=-359.30, y=58.00, z=-338.50], EntityHuman['Docm77'/18746, l='MpServer', x=-336.50, y=8.00, z=-260.50], EntityMobEnderman['Enderman'/19727, l='MpServer', x=-246.84, y=19.00, z=-324.34], EntityBat['Bat'/17402, l='MpServer', x=-315.75, y=7.75, z=-305.52], EntityCreeper['Creeper'/20257, l='MpServer', x=-273.50, y=14.00, z=-372.50], EntityCreeper['Creeper'/20258, l='MpServer', x=-273.50, y=14.00, z=-374.50], EntityItem['item.item.dyePowder.black'/19472, l='MpServer', x=-326.22, y=60.13, z=-291.13], EntitySheep['Baabara'/3070, l='MpServer', x=-408.72, y=20.00, z=-414.97], EntitySheep['Baabara'/3056, l='MpServer', x=-317.50, y=20.00, z=-377.50], EntityConcussionCreeper['Concussion Creeper'/8094, l='MpServer', x=-308.50, y=17.00, z=-356.50], EntityHuman['Corosus'/18776, l='MpServer', x=-330.38, y=37.00, z=-249.69], EntityGaiaMimic['Mimic'/18509, l='MpServer', x=-340.50, y=29.00, z=-381.50], EntityCreeper['Creeper'/8099, l='MpServer', x=-270.63, y=28.00, z=-408.91], EntityHuman['SkythekidRS'/3034, l='MpServer', x=-372.91, y=22.00, z=-446.38], EntityHuman['Soaryn'/19013, l='MpServer', x=-348.50, y=12.00, z=-246.50], EntityMinecartChest['entity.MinecartChest.name'/3039, l='MpServer', x=-387.50, y=9.34, z=-301.50], EntityZombie['Zombie'/19293, l='MpServer', x=-332.31, y=23.00, z=-256.50], EntityZombie['Zombie'/19292, l='MpServer', x=-336.44, y=27.00, z=-264.00], EntityMobEnderman['Enderman'/18828, l='MpServer', x=-350.34, y=22.00, z=-394.97], EntityBat['Bat'/18299, l='MpServer', x=-381.04, y=49.00, z=-302.25], EntityGaiaMimic['Mimic'/19672, l='MpServer', x=-322.50, y=11.00, z=-328.50], EntityHuman['MineMaarten'/19123, l='MpServer', x=-441.50, y=32.00, z=-385.50], EntityItem['item.item.ganyssurface.poop'/12518, l='MpServer', x=-285.34, y=63.13, z=-306.16], EntityHuman['FuriousDestroyer'/19124, l='MpServer', x=-439.50, y=32.00, z=-385.50], EntitySquid['Squid'/18573, l='MpServer', x=-284.50, y=58.38, z=-297.50], EntityMinecartChest['entity.MinecartChest.name'/2599, l='MpServer', x=-308.50, y=10.50, z=-285.50], EntitySquid['Squid'/18569, l='MpServer', x=-327.91, y=60.00, z=-286.84], EntityWitch['Witch'/19391, l='MpServer', x=-357.50, y=20.00, z=-256.31], EntityZombie['Zombie'/26160, l='MpServer', x=16.10, y=-17.62, z=-56.85], EntitySquid['Squid'/18567, l='MpServer', x=-326.50, y=60.03, z=-289.53], EntityMinecartChest['entity.MinecartChest.name'/2600, l='MpServer', x=-312.88, y=20.34, z=-271.50], EntityItem['item.item.dyePowder.black'/16897, l='MpServer', x=-401.00, y=61.13, z=-309.59], EntityHuman['_tommo_'/19338, l='MpServer', x=-373.91, y=14.46, z=-315.59], EntitySheep['Baabara'/2591, l='MpServer', x=-323.53, y=15.00, z=-268.09], EntityMinecartChest['entity.MinecartChest.name'/2585, l='MpServer', x=-321.50, y=15.34, z=-280.75], EntityWingedFireDemon['Winged Fire Demon'/2584, l='MpServer', x=-331.16, y=32.00, z=-290.78], EntityItem['item.item.bone'/11581, l='MpServer', x=-316.41, y=15.13, z=-280.16], EntityBileDemon['Bile Demon'/2572, l='MpServer', x=-338.19, y=31.00, z=-287.94], EntityWingedFireDemon['Winged Fire Demon'/2570, l='MpServer', x=-337.00, y=30.00, z=-292.28], EntityWingedFireDemon['Winged Fire Demon'/2571, l='MpServer', x=-340.59, y=31.00, z=-297.56], EntitySkeleton['Skeleton'/18237, l='MpServer', x=-313.50, y=33.00, z=-266.50], EntityZombie['Zombie'/19433, l='MpServer', x=-319.50, y=15.00, z=-278.50], EntityHuman['WayofFlowingTime'/18236, l='MpServer', x=-312.50, y=33.00, z=-261.50], EntityZombie['Zombie'/19432, l='MpServer', x=-321.50, y=15.00, z=-274.50], EntitySkeleton['Skeleton'/18238, l='MpServer', x=-312.50, y=33.00, z=-264.50], EntityBat['Bat'/17965, l='MpServer', x=-293.09, y=31.61, z=-263.42], EntitySkeleton['Skeleton'/19840, l='MpServer', x=-364.50, y=22.00, z=-391.50], EntityCreeper['Creeper'/20154, l='MpServer', x=-311.03, y=18.00, z=-257.44], EntitySheep['Baabara'/3089, l='MpServer', x=-424.38, y=32.00, z=-284.47], EntityZombie['Zombie'/18641, l='MpServer', x=-364.50, y=21.00, z=-269.50], Entity_Shooter['Twice-Cursed Rocket Skeleton'/19613, l='MpServer', x=-315.50, y=25.00, z=-403.50], EntityCreeper['Creeper'/18642, l='MpServer', x=-366.00, y=14.00, z=-276.50], EntityHuman['Cojomax99'/20157, l='MpServer', x=-366.50, y=21.00, z=-271.50], EntityZombie['Zombie'/3085, l='MpServer', x=-365.50, y=20.00, z=-255.50], EntityBat['Bat'/19444, l='MpServer', x=-330.97, y=16.10, z=-401.25], EntityBat['Bat'/19445, l='MpServer', x=-333.05, y=14.08, z=-399.48], EntityBat['Bat'/19446, l='MpServer', x=-324.88, y=15.00, z=-394.11], EntityBat['Bat'/19447, l='MpServer', x=-327.75, y=16.10, z=-397.75], EntityItem['item.item.ganyssurface.poop'/12144, l='MpServer', x=-286.94, y=63.13, z=-306.16], EntitySheep['Baabara'/3077, l='MpServer', x=-324.47, y=15.00, z=-396.53], EntityZombie['Zombie'/20140, l='MpServer', x=-326.44, y=32.00, z=-284.13], EntitySquid['Squid'/15940, l='MpServer', x=-400.94, y=61.00, z=-308.41], EntitySheep['Sheep'/2641, l='MpServer', x=-286.60, y=63.00, z=-308.55], EntitySheep['Sheep'/2640, l='MpServer', x=-287.93, y=63.00, z=-306.07], EntitySheep['Sheep'/2642, l='MpServer', x=-287.91, y=63.00, z=-308.93], EntityXPOrb['Experience Orb'/15450, l='MpServer', x=-318.50, y=26.25, z=-453.50], EntityItem['item.item.dyePowder.black'/16960, l='MpServer', x=-385.53, y=60.13, z=-283.97], EntityMinecartChest['entity.MinecartChest.name'/3132, l='MpServer', x=-376.13, y=9.34, z=-285.50], EntityItem['item.item.ganyssurface.poop'/13240, l='MpServer', x=-286.38, y=63.13, z=-307.53], EntitySkeleton['Skeleton'/19892, l='MpServer', x=-332.84, y=15.00, z=-289.66], EntitySkeleton['Skeleton'/19893, l='MpServer', x=-335.50, y=15.00, z=-291.50], EntityHuman['xbony2'/19418, l='MpServer', x=-316.66, y=10.00, z=-287.66], EntitySheep['Sheep'/2630, l='MpServer', x=-287.91, y=63.00, z=-308.93], EntitySheep['Sheep'/2631, l='MpServer', x=-285.07, y=63.00, z=-306.07], EntitySheep['Sheep'/2632, l='MpServer', x=-287.93, y=63.00, z=-306.07], EntitySheep['Sheep'/2633, l='MpServer', x=-287.93, y=63.00, z=-307.70], EntitySheep['Sheep'/2634, l='MpServer', x=-285.07, y=63.00, z=-306.74], EntitySheep['Sheep'/2635, l='MpServer', x=-285.07, y=63.00, z=-307.52], EntityZombie['Zombie'/19896, l='MpServer', x=-337.50, y=15.00, z=-289.50], EntitySheep['Sheep'/2636, l='MpServer', x=-286.72, y=63.00, z=-306.09], EntityZombie['Zombie'/19897, l='MpServer', x=-292.50, y=20.00, z=-377.50], EntitySheep['Sheep'/2637, l='MpServer', x=-285.09, y=63.00, z=-308.91], EntitySheep['Sheep'/2638, l='MpServer', x=-286.95, y=63.00, z=-307.44], EntityClientPlayerMP['baddogg1231'/15437, l='MpServer', x=-346.16, y=56.62, z=-333.69], EntitySheep['Sheep'/2639, l='MpServer', x=-286.17, y=63.00, z=-307.32]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Using AE2 rev3 beta 5
ThaumicEnergistics 1.0.0.1

**Comment by baddogg1231** [comment]
Turns out updating to Java 8 resolved the issue.

**Comment by Zsashas** [comment]
But why is J8 needed?

**Comment by XFactHD** [comment]
I think he is using an outdated version where Nividica was using a method from java 8. The latest version should work with java 7.

**Comment by Zsashas** [comment]
But the latest version on CurseForge says it requires Java 8...

**Comment by XFactHD** [comment]
Even if it needs java 8, where is the problem with using java 8?

**Comment by Zsashas** [comment]
Well, for me, the current issue is Chromaticraft is crashing for unknown reasons with Java 8. https://goo.gl/8ZtGxA
