### ISSUE TITLE
Cant handle package - find no other solution

### ISSUE THREAD

**Issue by SkallGodis** [Nividica/ThaumicEnergistics#311]
Hi,

I've recently tried this addon to Thaumcraft and AE2 on my server, and somehow whenever i want to enter a terminal (or clickable thing) i get a fatal error and get kicked from the server. It also seems, on what i can understand from the report from the console that it's all about a "cant handle package" issue. Tried troubleshooting it via internet with no success, and thats why i am here. Thanks for all help!

This is what my console says:

[16-05-2016 09:01:43] [FML]: FMLIndexedMessageCodec exception caught
[16-05-2016 09:01:43] java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
[16-05-2016 09:01:43] at thaumicenergistics.common.network.NetworkHandler.getPacketClassFromID(NetworkHandler.java:55) ~[NetworkHandler.class:?]
[16-05-2016 09:01:43] at thaumicenergistics.common.network.WrapperPacket.fromBytes(WrapperPacket.java:53) ~[WrapperPacket.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[16-05-2016 09:01:43] at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[16-05-2016 09:01:43] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[16-05-2016 09:01:43] at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[16-05-2016 09:01:43] at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[16-05-2016 09:01:43] at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[16-05-2016 09:01:43] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[16-05-2016 09:01:43] at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[16-05-2016 09:01:43] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[16-05-2016 09:01:43] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[16-05-2016 09:01:43] at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
[16-05-2016 09:01:43] at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16-05-2016 09:01:43] [FML]: SimpleChannelHandlerWrapper exception
[16-05-2016 09:01:43] java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
[16-05-2016 09:01:43] at thaumicenergistics.common.network.NetworkHandler.getPacketClassFromID(NetworkHandler.java:55) ~[NetworkHandler.class:?]
[16-05-2016 09:01:43] at thaumicenergistics.common.network.WrapperPacket.fromBytes(WrapperPacket.java:53) ~[WrapperPacket.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[16-05-2016 09:01:43] at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[16-05-2016 09:01:43] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[16-05-2016 09:01:43] at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[16-05-2016 09:01:43] at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[16-05-2016 09:01:43] at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[16-05-2016 09:01:43] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[16-05-2016 09:01:43] at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[16-05-2016 09:01:43] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[16-05-2016 09:01:43] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[16-05-2016 09:01:43] at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
[16-05-2016 09:01:43] at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16-05-2016 09:01:43] [FML]: There was a critical exception handling a packet on channel thaumicenergistics
[16-05-2016 09:01:43] java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
[16-05-2016 09:01:43] at thaumicenergistics.common.network.NetworkHandler.getPacketClassFromID(NetworkHandler.java:55) ~[NetworkHandler.class:?]
[16-05-2016 09:01:43] at thaumicenergistics.common.network.WrapperPacket.fromBytes(WrapperPacket.java:53) ~[WrapperPacket.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[16-05-2016 09:01:43] at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[16-05-2016 09:01:43] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[16-05-2016 09:01:43] at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[16-05-2016 09:01:43] at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[16-05-2016 09:01:43] at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[16-05-2016 09:01:43] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
[16-05-2016 09:01:43] at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
[16-05-2016 09:01:43] at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[16-05-2016 09:01:43] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[16-05-2016 09:01:43] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[16-05-2016 09:01:43] at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
[16-05-2016 09:01:43] at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
[16-05-2016 09:01:43] at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16-05-2016 09:01:44] SkallGodis lost connection: TextComponent{text='A fatal error has occured, this connection is terminated', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Comment by Nividica** [comment]
See #297

**Comment by SkallGodis** [comment]
I have java 8 on both server and my computer. Are you absolutely confident that it is java that is the problem?

**Comment by Nividica** [comment]
The root error is
java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

getOrDefault was introduced in Java 8. Check your launch log, it should list the Java executable path used to launch the server.
