### ISSUE TITLE
My Minecraft crashed when I used "ME Essentia Terminal". 

### ISSUE THREAD

**Issue by Matsunon** [Nividica/ThaumicEnergistics#385]
Hello Specialists,

My Minecraft crashed when I used "ME Essentia Terminal". 

[Jar]-[AE2 cable]-[ME Interface]-[ME Drive]-[ME Essentia Terminal]

Please see the crash report bellow.
Caused by: java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.isEmpty()Z
	at thaumicenergistics.api.EssentiaStack.readFromNBT(EssentiaStack.java:69)
	at thaumicenergistics.integration.appeng.AEEssentiaStack.fromNBT(AEEssentiaStack.java:61)
	at thaumicenergistics.integration.appeng.ThEAppliedEnergistics$EssentiaStorageChannel.createFromNBT(ThEAppliedEnergistics.java:96)
	at thaumicenergistics.integration.appeng.ThEAppliedEnergistics$EssentiaStorageChannel.createFromNBT(ThEAppliedEnergistics.java:66)
	at appeng.me.storage.BasicCellInventory.loadCellItem(BasicCellInventory.java:262)
	at appeng.me.storage.AbstractCellInventory.loadCellItems(AbstractCellInventory.java:201)
	at appeng.me.storage.AbstractCellInventory.getCellItems(AbstractCellInventory.java:101)
	at appeng.me.storage.AbstractCellInventory.getAvailableItems(AbstractCellInventory.java:222)
	at appeng.me.storage.MEPassThrough.getAvailableItems(MEPassThrough.java:69)
	at appeng.me.storage.MEInventoryHandler.getAvailableItems(MEInventoryHandler.java:128)
	at appeng.me.storage.MEInventoryHandler.getAvailableItems(MEInventoryHandler.java:128)
	at appeng.me.cache.GridStorageCache$CellChangeTrackerRecord.<init>(GridStorageCache.java:322)
	at appeng.me.cache.GridStorageCache$CellChangeTracker.postChanges(GridStorageCache.java:338)
	at appeng.me.cache.GridStorageCache.lambda$addCellProvider$2(GridStorageCache.java:184)
	at java.util.IdentityHashMap.forEach(Unknown Source)
	at appeng.me.cache.GridStorageCache.addCellProvider(GridStorageCache.java:180)
	at appeng.me.cache.GridStorageCache.cellUpdate(GridStorageCache.java:243)
	... 37 more

Best Regards,
Matsunon

**Comment by BrockWS** [comment]
Could you please upload the full debug.log file (to pastebin, gist, etc) and please specify the version of forge and Thaumic Energistics.

**Comment by Matsunon** [comment]
Hi BrockWS,

Please find the debug.log.
[debug.log](https://github.com/Nividica/ThaumicEnergistics/files/3621385/debug.log)


Forge Version : 14.23.5.2846
TE2 Version : (AE2-RV6) Thaumic Energistics 2.2.3

Thanks,
Matsunon

**Comment by BrockWS** [comment]
I don't see the crash there, you need to post the debug.log right after the crash since it gets reset every game launch. Could you also provide the crash report file inside the crash-reports folder

**Comment by RStieber** [comment]
I have a [single player] world running in FTB Sky Odyssey, and just installed TE because I wanted better thaumcraft support with AE2.  I'm now getting this error as well after I had imported just a few (I think 3?) essentia into my system.  Clicked on the Essentia Terminal, game froze; force closed it and re-opened, game crashes each time the world loads now.  I've tried several different forge versions, AE2 Rev6 and Rev7, all no go.  Including the crash log, as well as the latest.log (I don't know where the debug.log file is?)

[crash-2019-10-15_12.00.31-server.txt](https://github.com/Nividica/ThaumicEnergistics/files/3730616/crash-2019-10-15_12.00.31-server.txt)

[latest.log](https://github.com/Nividica/ThaumicEnergistics/files/3730617/latest.log)

Of note:  When I first added TE to the pack, I was on AE2 Rev6 and Forge 14.23.5.2815.  That's when I clicked on the Essentia Terminal and had Minecraft freeze; updated then after reading a bit more carefully to AE2 Rev7 and Forge 14.23.5.2838, and then mixing and matching versions with no success.

**Comment by Princess-Moeka** [comment]
I have the same problem as Matsunon. 
[Debuglog](https://www.dropbox.com/s/f3g0p5gujx258jg/debug.log?dl=1)

**Comment by BrockWS** [comment]
Sorry for the delay. I cannot replicate the crash even in Sky Odyssey. It might be a coremod but I can't see why one would edit the class.

**Comment by perillamint** [comment]
Sorry for the necrobumping thread but note that you must not include thaumicenergistics-<blah>-api.jar in your mods folder. In my case, it was the problem.
